import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const artifacts = [
  { name: 'MultiEscrow', sourceName: 'contracts/MultiEscrow.sol', moduleName: 'multiEscrow', constName: 'multiEscrow' },
  { name: 'MultiAuction', sourceName: 'contracts/MultiAuction.sol', moduleName: 'multiAuction', constName: 'multiAuction' },
]
const registryPath = join(root, 'src', 'registry.ts')
const indexPath = join(root, 'src', 'index.ts')
const packagePath = join(root, 'package.json')

function normalizeHex(value, field) {
  if (typeof value !== 'string' || !value.startsWith('0x')) {
    throw new Error(`${field} must be a 0x-prefixed hex string`)
  }
  return value
}

function sha256HexBytes(hex) {
  const bytes = Buffer.from(hex.slice(2), 'hex')
  return `0x${createHash('sha256').update(bytes).digest('hex')}`
}

const pkg = JSON.parse(readFileSync(packagePath, 'utf8'))
const generated = []

for (const item of artifacts) {
  const artifactPath = join(root, 'artifacts', `${item.name}.json`)
  const abiPath = join(root, 'artifacts', `${item.name}.abi.json`)
  const modulePath = join(root, 'src', `${item.moduleName}.ts`)
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'))
  const abi = artifact.abi
  if (!Array.isArray(abi)) throw new Error(`${item.name} artifact does not contain an ABI array`)

  const bytecode = normalizeHex(artifact.bytecode, `${item.name} bytecode`)
  const deployedBytecode = normalizeHex(artifact.deployedBytecode, `${item.name} deployedBytecode`)
  const runtimeBytecodeHash = sha256HexBytes(deployedBytecode)

  writeFileSync(abiPath, `${JSON.stringify(abi, null, 2)}\n`)
  writeFileSync(
    modulePath,
    `// Generated by scripts/generate.mjs. Do not edit by hand.\n` +
      `\n` +
      `export const ${item.constName}Abi = ${JSON.stringify(abi, null, 2)} as const\n` +
      `\n` +
      `export const ${item.constName}Bytecode = ${JSON.stringify(bytecode)} as const\n` +
      `\n` +
      `export const ${item.constName}DeployedBytecode = ${JSON.stringify(deployedBytecode)} as const\n` +
      `\n` +
      `export const ${item.constName}RuntimeBytecodeHash = ${JSON.stringify(runtimeBytecodeHash)} as const\n`,
  )

  generated.push({
    ...item,
    artifact,
    bytecode,
    deployedBytecode,
    runtimeBytecodeHash,
  })
}

writeFileSync(
  registryPath,
  generated.map(item =>
    `import {\n` +
      `  ${item.constName}Abi,\n` +
      `  ${item.constName}Bytecode,\n` +
      `  ${item.constName}DeployedBytecode,\n` +
      `  ${item.constName}RuntimeBytecodeHash,\n` +
      `} from './${item.moduleName}.js'\n`,
  ).join('') +
    `\n` +
    `export type MarketplaceContractArtifact = {\n` +
    `  readonly name: string\n` +
    `  readonly version: string\n` +
    `  readonly sourceName: string\n` +
    `  readonly abi: readonly unknown[]\n` +
    `  readonly bytecode: \`0x\${string}\`\n` +
    `  readonly deployedBytecode: \`0x\${string}\`\n` +
    `  readonly runtimeBytecodeHash: \`0x\${string}\`\n` +
    `}\n` +
    generated.map(item =>
      `\n` +
      `export const ${item.constName}Contract = {\n` +
      `  name: ${JSON.stringify(item.artifact.contractName ?? item.name)},\n` +
      `  version: ${JSON.stringify(pkg.version)},\n` +
      `  sourceName: ${JSON.stringify(item.artifact.sourceName ?? item.sourceName)},\n` +
      `  abi: ${item.constName}Abi,\n` +
      `  bytecode: ${item.constName}Bytecode,\n` +
      `  deployedBytecode: ${item.constName}DeployedBytecode,\n` +
      `  runtimeBytecodeHash: ${item.constName}RuntimeBytecodeHash,\n` +
      `} satisfies MarketplaceContractArtifact\n`,
    ).join('') +
    `\n` +
    `export const marketplaceContractRegistry = {\n` +
    generated.map(item => `  [${item.constName}RuntimeBytecodeHash]: ${item.constName}Contract,\n`).join('') +
    `} as const\n` +
    `\n` +
    generated.map(item =>
      `export function find${item.name}ByRuntimeBytecodeHash(\n` +
      `  runtimeBytecodeHash: string | null | undefined,\n` +
      `): MarketplaceContractArtifact | undefined {\n` +
      `  if (!runtimeBytecodeHash) return undefined\n` +
      `  const normalized = runtimeBytecodeHash.toLowerCase()\n` +
      `  return normalized === ${item.constName}RuntimeBytecodeHash ? ${item.constName}Contract : undefined\n` +
      `}\n` +
      `\n`,
    ).join('') +
    `export function findMarketplaceContractByRuntimeBytecodeHash(\n` +
    `  runtimeBytecodeHash: string | null | undefined,\n` +
    `): MarketplaceContractArtifact | undefined {\n` +
    `  if (!runtimeBytecodeHash) return undefined\n` +
    `  return marketplaceContractRegistry[runtimeBytecodeHash.toLowerCase() as keyof typeof marketplaceContractRegistry]\n` +
    `}\n`,
)

writeFileSync(indexPath, generated.map(item => `export * from './${item.moduleName}.js'\n`).join('') + `export * from './registry.js'\n`)
