import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const artifactPath = join(root, 'artifacts', 'MultiEscrow.json')
const abiPath = join(root, 'artifacts', 'MultiEscrow.abi.json')
const multiEscrowPath = join(root, 'src', 'multiEscrow.ts')
const registryPath = join(root, 'src', 'registry.ts')
const packagePath = join(root, 'package.json')

function normalizeHex(value, field) {
  if (typeof value !== 'string' || !value.startsWith('0x')) {
    throw new Error(`${field} must be a 0x-prefixed hex string`)
  }
  return value
}

function sha256HexBytes(hex) {
  const bytes = Buffer.from(hex.slice(2), 'hex')
  return `0x${createHash('sha256').update(bytes).digest('hex')}`
}

const pkg = JSON.parse(readFileSync(packagePath, 'utf8'))
const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'))
const abi = artifact.abi
if (!Array.isArray(abi)) throw new Error('MultiEscrow artifact does not contain an ABI array')

const bytecode = normalizeHex(artifact.bytecode, 'bytecode')
const deployedBytecode = normalizeHex(artifact.deployedBytecode, 'deployedBytecode')
const runtimeBytecodeHash = sha256HexBytes(deployedBytecode)

writeFileSync(abiPath, `${JSON.stringify(abi, null, 2)}\n`)

writeFileSync(
  multiEscrowPath,
  `// Generated by scripts/generate.mjs. Do not edit by hand.\n` +
    `\n` +
    `export const multiEscrowAbi = ${JSON.stringify(abi, null, 2)} as const\n` +
    `\n` +
    `export const multiEscrowBytecode = ${JSON.stringify(bytecode)} as const\n` +
    `\n` +
    `export const multiEscrowDeployedBytecode = ${JSON.stringify(deployedBytecode)} as const\n` +
    `\n` +
    `export const multiEscrowRuntimeBytecodeHash = ${JSON.stringify(runtimeBytecodeHash)} as const\n`,
)

writeFileSync(
  registryPath,
  `import {\n` +
    `  multiEscrowAbi,\n` +
    `  multiEscrowBytecode,\n` +
    `  multiEscrowDeployedBytecode,\n` +
    `  multiEscrowRuntimeBytecodeHash,\n` +
    `} from './multiEscrow.js'\n` +
    `\n` +
    `export type MarketplaceContractArtifact = {\n` +
    `  readonly name: string\n` +
    `  readonly version: string\n` +
    `  readonly sourceName: string\n` +
    `  readonly abi: readonly unknown[]\n` +
    `  readonly bytecode: \`0x\${string}\`\n` +
    `  readonly deployedBytecode: \`0x\${string}\`\n` +
    `  readonly runtimeBytecodeHash: \`0x\${string}\`\n` +
    `}\n` +
    `\n` +
    `export const multiEscrowContract = {\n` +
    `  name: ${JSON.stringify(artifact.contractName ?? 'MultiEscrow')},\n` +
    `  version: ${JSON.stringify(pkg.version)},\n` +
    `  sourceName: ${JSON.stringify(artifact.sourceName ?? 'contracts/MultiEscrow.sol')},\n` +
    `  abi: multiEscrowAbi,\n` +
    `  bytecode: multiEscrowBytecode,\n` +
    `  deployedBytecode: multiEscrowDeployedBytecode,\n` +
    `  runtimeBytecodeHash: multiEscrowRuntimeBytecodeHash,\n` +
    `} satisfies MarketplaceContractArtifact\n` +
    `\n` +
    `export const multiEscrowRegistry = {\n` +
    `  [multiEscrowRuntimeBytecodeHash]: multiEscrowContract,\n` +
    `} as const\n` +
    `\n` +
    `export function findMultiEscrowByRuntimeBytecodeHash(\n` +
    `  runtimeBytecodeHash: string | null | undefined,\n` +
    `): MarketplaceContractArtifact | undefined {\n` +
    `  if (!runtimeBytecodeHash) return undefined\n` +
    `  return multiEscrowRegistry[runtimeBytecodeHash.toLowerCase() as keyof typeof multiEscrowRegistry]\n` +
    `}\n`,
)

